'use strict';
const el=id=>document.getElementById(id);let result=null;
async function workbook(id){const f=el(id).files[0];if(!f)throw Error('Choose the '+id+' file.');if(f.size>25*1024*1024)throw Error('File exceeds 25 MB.');return XLSX.read(await f.arrayBuffer(),{type:'array',raw:true,cellDates:false});}
function objects(wb,name){const s=wb.Sheets[name||wb.SheetNames[0]];if(!s)throw Error('Missing worksheet: '+name);return XLSX.utils.sheet_to_json(s,{defval:'',raw:true});}
function crmRows(wb,kind){const r=objects(wb);for(const h of ['Record Id','Portfolio As-of Date',kind==='contacts'?'Account Name.id':'Account Name'])if(!r.length||!(h in r[0]))throw Error('CRM '+kind+' export missing '+h);for(const row of r){const d=row['Portfolio As-of Date'];if(typeof d==='number'){const p=XLSX.SSF.parse_date_code(d);row['Portfolio As-of Date']=p?`${p.y}-${String(p.m).padStart(2,'0')}-${String(p.d).padStart(2,'0')}`:'';}}return r;}
function table(target,rows){target.replaceChildren();if(!rows.length){target.textContent='None.';return;}const t=document.createElement('table'),head=t.createTHead().insertRow();for(const c of Object.keys(rows[0])){const th=document.createElement('th');th.textContent=c;head.append(th);}for(const r of rows){const tr=t.insertRow();for(const v of Object.values(r)){tr.insertCell().textContent=String(v??'');}}target.append(t);}
function download(name,rows){const a=document.createElement('a'),url=URL.createObjectURL(new Blob([MProfitConverter.csv(rows)],{type:'text/csv;charset=utf-8'}));a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
for(const i of document.querySelectorAll('input'))i.addEventListener('change',()=>{result=null;el('results').hidden=true;el('message').textContent='';});
el('convert').onclick=async()=>{result=null;el('results').hidden=true;el('convert').disabled=true;el('message').textContent='Reading files…';try{
 const m=el('mapping').files[0];if(!m)throw Error('Choose the reviewed mapping JSON.');const mapping=JSON.parse(await m.text());
 const report=await workbook('report'),contacts=crmRows(await workbook('contacts'),'contacts'),accounts=crmRows(await workbook('accounts'),'accounts');
 result=MProfitConverter.convert(objects(report,'Raw data'),mapping,contacts,accounts,el('date').value);
 el('summary').replaceChildren();for(const [label,value] of [['Source positions',result.positions],['Family updates',result.familyRows.length],['Client updates',result.contactRows.length],['Total current value',result.sourceValue],['Client current value',result.contactValue],['Held client value',result.heldValue]]){const d=document.createElement('div');d.className='metric';d.textContent=label;const b=document.createElement('strong');b.textContent=Number(value).toLocaleString('en-IN',{maximumFractionDigits:2});d.append(b);el('summary').append(d);}
 table(el('excluded'),result.excluded.map(r=>({'Source family':r.family,'Portfolio':r.portfolio,'Current value':Math.round(r.value*100)/100,'Reason':r.reason})));table(el('preview'),result.contactRows.slice(0,8));el('results').hidden=false;el('message').textContent='Prepared. Review exclusions before downloading.';
 }catch(e){el('message').textContent=e.message;}finally{el('convert').disabled=false;}};
el('family').onclick=()=>result&&download('family-update.csv',result.familyRows);el('member').onclick=()=>result&&download('member-update.csv',result.contactRows);el('exceptions').onclick=()=>result&&download('excluded-portfolios.csv',result.excluded);
