// Client matching controls. Draft edits affect this session; shared updates require publication.
let reviewRaw=null;
function savePrivateSetup(){setup.updatedAt=new Date().toISOString();reset();el('unchanged').checked=false;renderSetup();el('refresh-status').textContent='Changes applied to this session. Download the updated client list for publication so everyone receives these changes.';}
async function rawForReview(){const wb=await workbook(),sheet=wb.Sheets['Raw data'];if(!sheet)throw Error('Choose the complete MProfit workbook with Raw data.');return XLSX.utils.sheet_to_json(sheet,{defval:'',raw:true});}
function choice(items,label){const select=document.createElement('select');select.setAttribute('aria-label',label);select.append(new Option('Select the correct CRM record…',''));for(const item of items)select.append(new Option(item.label,item.id));return select;}
function renderMatches(){const panel=el('match-list');panel.replaceChildren();if(!setup||!reviewRaw)return;const pending=MProfitMatching.review(reviewRaw,setup);el('matching-status').textContent=pending.families.length+' family matches and '+pending.portfolios.length+' client matches need review.';
 for(const item of pending.families){const card=document.createElement('div');card.className='match-card';const title=document.createElement('h3');title.textContent=item.family;const note=document.createElement('p');note.textContent=item.reason+'. Select the CRM family Account. This does not create or change CRM records.';const select=choice(setup.accounts.map(a=>({id:a['Record Id'],label:a['Account Name']+' · '+a['Record Id']})),'CRM family for '+item.family);const save=document.createElement('button');save.textContent='Save family match';save.onclick=()=>{try{MProfitMatching.setFamily(setup,item.family,select.value);savePrivateSetup();renderMatches();}catch(e){el('matching-status').textContent=e.message;}};card.append(title,note,select,save);panel.append(card);}
 for(const item of pending.portfolios){const card=document.createElement('div');card.className='match-card';const title=document.createElement('h3');title.textContent=item.portfolio+' — '+item.family;const note=document.createElement('p');note.textContent=item.reason+'. Verify ownership before saving; joint or ambiguous portfolios must stay unmatched until confirmed.';const candidates=setup.contacts.filter(c=>c['Account Name.id']===item.accountId);const select=choice(candidates.map(c=>({id:c['Record Id'],label:(c['Contact Name']||[c['First Name'],c['Last Name']].filter(Boolean).join(' '))+' · '+c['Record Id']})),'CRM client for '+item.portfolio);const save=document.createElement('button');save.textContent='Save client match';save.onclick=()=>{try{MProfitMatching.setHolder(setup,item.family,item.portfolio,select.value);savePrivateSetup();renderMatches();}catch(e){el('matching-status').textContent=e.message;}};card.append(title,note,select,save);if(!candidates.length){const p=document.createElement('p');p.textContent='No Contacts in this family. Create/associate the Contact in CRM, then refresh the Contacts list below.';card.append(p);}panel.append(card);}
}
el('review-matches').onclick=async()=>{try{if(!setup)throw Error('Refresh this page to load the shared client list.');reviewRaw=await rawForReview();el('matching').hidden=false;renderMatches();}catch(e){el('message').textContent=e.message;}};
el('report').addEventListener('change',()=>{reviewRaw=null;el('matching').hidden=true;});
for(const kind of ['contacts','accounts'])el('refresh-'+kind).onchange=async()=>{try{
 if(!setup)throw Error('Refresh this page to load the shared client list.');const f=el('refresh-'+kind).files[0];if(!f)return;if(f.size>25*1024*1024)throw Error('Export exceeds 25 MB.');const wb=XLSX.read(await f.arrayBuffer(),{type:'array',raw:true}),rows=XLSX.utils.sheet_to_json(wb.Sheets[wb.SheetNames[0]],{defval:'',raw:true});
 const fields=kind==='contacts'?['Record Id','Contact Name','First Name','Last Name','Account Name.id','Portfolio As-of Date']:['Record Id','Account Name','Portfolio As-of Date'];const required=kind==='contacts'?['Record Id','Account Name.id','Portfolio As-of Date']:fields;
 if(!rows.length||required.some(h=>!(h in rows[0])))throw Error('Use a full '+kind+' export containing '+required.join(', ')+'.');
 const minimal=rows.map(r=>Object.fromEntries(fields.map(h=>{let v=r[h]??'';if(h==='Portfolio As-of Date'&&typeof v==='number'){const d=XLSX.SSF.parse_date_code(v);if(!d)throw Error('Invalid portfolio date.');v=d.y+'-'+String(d.m).padStart(2,'0')+'-'+String(d.d).padStart(2,'0');}return [h,v];})));
 const next=JSON.parse(JSON.stringify(setup));next[kind]=minimal;validateSetup(next);next[kind+'RefreshedAt']=new Date().toISOString();setup=next;savePrivateSetup();el('refresh-status').textContent='Applied '+minimal.length+' '+kind+' to this session. Download the updated client list for publication to share these changes.';if(reviewRaw)renderMatches();
 }catch(e){el('refresh-status').textContent=e.message;}};
el('backup-setup').onclick=()=>{if(!setup)return;const url=URL.createObjectURL(new Blob([JSON.stringify(setup)],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download='Katas-Converter-Private-Setup.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
for(const id of ['setup-file','forget'])el(id).addEventListener(id==='forget'?'click':'change',()=>{reviewRaw=null;el('matching').hidden=true;});

